parameters:
    my_mongo_database: "command-watcher"
    my_mongo_dsn: "mongodb://172.17.0.5:27017/command-watcher"

services:
    sowbiba_command_watcher.command_listener:
        class: Sowbiba\CommandWatcherBundle\Listener\CommandListener
        arguments:
            - '@sowbiba_command_watcher.stop_watch'
            - '@sowbiba_command_watcher.log_writer'
            - '%sowbiba_command_watcher.commands%'
        tags:
            - { name: kernel.event_listener, event: console.command, method: onCommandStart }
            - { name: kernel.event_listener, event: console.terminate, method: onCommandEnd }


    sowbiba_command_watcher.stop_watch:
        class: Symfony\Component\Stopwatch\Stopwatch

#    sowbiba_command_watcher.log_reader:
#        class: Sowbiba\CommandWatcherBundle\Reader\FileReader
#        arguments:
#            - %sowbiba_command_watcher.commands%
#            - "app/tmp"
#            - ""
#
#    sowbiba_command_watcher.log_writer:
#        class: Sowbiba\CommandWatcherBundle\Writer\FileWriter
#        arguments:
#            - "app/tmp"
#            - ""


    sowbiba_command_watcher.log_reader:
        class: Sowbiba\CommandWatcherBundle\Logger\Mongo\MongoReader
        arguments:
            - "%my_mongo_dsn%"
            - "%my_mongo_database%"
            - %sowbiba_command_watcher.commands%

    sowbiba_command_watcher.log_writer:
        class: Sowbiba\CommandWatcherBundle\Logger\Mongo\MongoWriter
        arguments:
            - "%my_mongo_dsn%"
            - "%my_mongo_database%"