parameters:
    my_mongo_database: "command-watcher"
    my_mongo_dsn: "mongodb://172.17.0.5:27017/command-watcher"

services:
    sowbiba_command_watcher.watcher:
        class: Sowbiba\CommandWatcherBundle\Watcher\Watcher
        arguments:
            - '@sowbiba_command_watcher.log_writer'

    sowbiba_command_watcher.command_listener:
        class: Sowbiba\CommandWatcherBundle\Listener\CommandListener
        arguments:
            - '@sowbiba_command_watcher.watcher'
            - '%sowbiba_command_watcher.commands%'
        tags:
            - { name: kernel.event_listener, event: console.command, method: onCommandStart }
            - { name: kernel.event_listener, event: console.terminate, method: onCommandEnd }

    sowbiba_command_watcher.request_listener:
        class: Sowbiba\CommandWatcherBundle\Listener\RequestListener
        arguments:
            - '@sowbiba_command_watcher.watcher'
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onRequestStart }
            - { name: kernel.event_listener, event: kernel.finish_request, method: onFinishRequest }

    sowbiba_command_watcher.log_reader:
        class: Sowbiba\CommandWatcherBundle\Logger\File\FileReader
        arguments:
            - "%kernel.root_dir%/tmp"
            - ""

    sowbiba_command_watcher.log_writer:
        class: Sowbiba\CommandWatcherBundle\Logger\File\FileWriter
        arguments:
            - "%kernel.root_dir%/tmp"
            - ""


#    sowbiba_command_watcher.log_reader:
#        class: Sowbiba\CommandWatcherBundle\Logger\Mongo\MongoReader
#        arguments:
#            - "%my_mongo_dsn%"
#            - "%my_mongo_database%"
#            - %sowbiba_command_watcher.commands%
#
#    sowbiba_command_watcher.log_writer:
#        class: Sowbiba\CommandWatcherBundle\Logger\Mongo\MongoWriter
#        arguments:
#            - "%my_mongo_dsn%"
#            - "%my_mongo_database%"